// RunsListPage — operator default landing page (PLAN §6, D12).
//
// On mount: fetch /runs-index.json (generated by scripts/07_runs_list.py) +
// /subject-aliases.json (opt-in, D16). Renders a table per IA §2.1; clicking
// a row navigates to the run detail with `?evidence=/sample-pack-<run_id>.json`
// (a per-run dev fixture; if missing the run page surfaces a 404 — that's the
// operator's signal to generate the pack via scripts/04_export_evidence_pack).
//
// Empty state shows the 3 commands the operator needs to populate the index.
// No links to dashboard dev-server commands — the operator is already running
// the dashboard if they're seeing this page.

import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { loadFromEmbedded } from "../lib/evidencePack";
import {
  formatSubject,
  loadSubjectAliases,
  type SubjectAliases,
} from "../lib/subjectAliases";

const ERC8004_REGISTRY = "0x7177a6867296406881E20d6647232314736Dd09A";
void ERC8004_REGISTRY; // not used directly here; reserved for future agent identity link

function basescanTxUrl(tx: string): string {
  // Base Sepolia is the only chain in v0.3 — same convention as RunPage.
  return `https://sepolia.basescan.org/tx/${tx}`;
}

// --- runs-index.json schema (mirrors PLAN §6 + tests/test_runs_list.py) ---

interface RunEntry {
  run_id: string;
  agent_id: string;
  subject_ref: string | null;
  started_at: string;
  ended_at: string | null;
  duration_ms: number | null;
  event_count: number;
  final_decision: string | null;
  anchor_tx: string;
  anchor_block: number;
  has_summary: boolean;
}

interface RunsIndex {
  version: string;
  generated_at: string;
  runs: RunEntry[];
}

type LoadState =
  | { kind: "loading" }
  | { kind: "missing" }                              // 404 — file not generated yet
  | { kind: "empty"; index: RunsIndex }              // file present but no runs
  | { kind: "ok"; index: RunsIndex }
  | { kind: "error"; message: string };

// --- formatters -----------------------------------------------------------

function formatDuration(ms: number | null): string {
  if (ms === null) return "—";
  if (ms < 1000) return `${ms} ms`;
  if (ms < 60_000) return `${(ms / 1000).toFixed(1)}s`;
  const seconds = Math.round(ms / 1000);
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  if (m < 60) return `${m}m ${s}s`;
  const h = Math.floor(m / 60);
  return `${h}h ${m % 60}m`;
}

function formatStartedAt(iso: string): string {
  // IA §5 rule 4: relative formats by recency.
  //   today HH:MM  / yesterday / Mar 12 / Mar 12, 2025 (cross-year)
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  const now = new Date();
  const startOfDay = (x: Date) =>
    new Date(x.getFullYear(), x.getMonth(), x.getDate()).getTime();
  const dayDiff = Math.round((startOfDay(now) - startOfDay(d)) / 86_400_000);
  const hh = String(d.getHours()).padStart(2, "0");
  const mm = String(d.getMinutes()).padStart(2, "0");
  if (dayDiff === 0) return `today ${hh}:${mm}`;
  if (dayDiff === 1) return "yesterday";
  const monthShort = d.toLocaleString("en-US", { month: "short" });
  if (d.getFullYear() === now.getFullYear()) {
    return `${monthShort} ${d.getDate()}`;
  }
  return `${monthShort} ${d.getDate()}, ${d.getFullYear()}`;
}

function decisionClasses(decision: string | null): string {
  if (decision === null) return "text-muted";
  const lower = decision.toLowerCase();
  if (lower === "reject") return "text-fail font-semibold";
  if (lower === "hire") return "text-ok font-semibold";
  return "text-muted font-semibold";
}

// --- data hook -------------------------------------------------------------

function useRunsListData(): {
  state: LoadState;
  aliases: SubjectAliases;
} {
  const [state, setState] = useState<LoadState>({ kind: "loading" });
  const [aliases, setAliases] = useState<SubjectAliases>({});

  useEffect(() => {
    let cancelled = false;

    void loadSubjectAliases().then((a) => {
      if (!cancelled) setAliases(a);
    });

    fetch("/runs-index.json", { headers: { Accept: "application/json" } })
      .then(async (res) => {
        if (cancelled) return;
        if (res.status === 404) {
          setState({ kind: "missing" });
          return;
        }
        if (!res.ok) {
          setState({
            kind: "error",
            message: `runs-index.json fetch returned HTTP ${res.status}`,
          });
          return;
        }
        try {
          const data = (await res.json()) as RunsIndex;
          if (!Array.isArray(data.runs)) {
            setState({
              kind: "error",
              message: "runs-index.json missing 'runs' array",
            });
            return;
          }
          if (data.runs.length === 0) {
            setState({ kind: "empty", index: data });
            return;
          }
          setState({ kind: "ok", index: data });
        } catch (err) {
          setState({
            kind: "error",
            message: err instanceof Error ? err.message : String(err),
          });
        }
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        setState({
          kind: "error",
          message: err instanceof Error ? err.message : String(err),
        });
      });

    return () => {
      cancelled = true;
    };
  }, []);

  return { state, aliases };
}

// --- subviews --------------------------------------------------------------

function PageHeader({ agentId }: { agentId: string | null }) {
  return (
    <div className="flex items-baseline justify-between gap-4 flex-wrap">
      <h1 className="text-2xl font-semibold">
        PromptSeal
        {agentId && <span className="text-muted"> · {agentId}</span>}
      </h1>
      <Link
        to="/load"
        className="text-sm text-accent no-underline hover:underline"
      >
        load pack ↗
      </Link>
    </div>
  );
}

function EmptyState({ reason }: { reason: "missing" | "empty" }) {
  // Same copy for both — the operator's next step is identical: run the
  // pipeline + regenerate the index. We just don't say "file not found"
  // because that confuses non-engineers.
  void reason;
  return (
    <section className="bg-panel border border-border rounded-lg p-8 text-center space-y-4">
      <div className="text-lg text-text">No runs yet.</div>
      <div className="text-sm text-muted space-y-2">
        <div>To populate this view:</div>
        <ol className="text-left max-w-md mx-auto space-y-1 list-decimal list-inside">
          <li>
            <code className="bg-bg px-1.5 py-0.5 rounded border border-border">
              python scripts/02_run_demo.py
            </code>
          </li>
          <li>
            <code className="bg-bg px-1.5 py-0.5 rounded border border-border">
              python scripts/03_anchor_run.py &lt;run_id&gt;
            </code>
          </li>
          <li>
            <code className="bg-bg px-1.5 py-0.5 rounded border border-border">
              python scripts/07_runs_list.py
            </code>
          </li>
        </ol>
      </div>
    </section>
  );
}

function ErrorBanner({ message }: { message: string }) {
  return (
    <section className="bg-fail/15 border border-fail/40 rounded-lg p-4">
      <div className="text-fail font-semibold">Failed to load runs list</div>
      <pre className="text-xs text-text/80 mt-2 whitespace-pre-wrap break-all">
        {message}
      </pre>
    </section>
  );
}

interface RowProps {
  run: RunEntry;
  aliases: SubjectAliases;
}

function RunsTableRow({ run, aliases }: RowProps) {
  // E7 Issue 1: row is a single click target. v0.3 originally wrapped each
  // cell in <Link>, which made the row look like 7 stacked hyperlinks
  // instead of one navigable unit. Switched to one onClick on <tr>; the
  // Anchored ✓ stays a real <a> (so middle/cmd-click opens basescan in a
  // new tab) and stopPropagation guards against the row click hijacking
  // its navigation. Trade-off: middle/cmd-click on the row no longer
  // opens /run/<id> in a new tab. Acceptable for v0.3 — operators iterate
  // in a single tab.
  const navigate = useNavigate();
  const subject = formatSubject(run.subject_ref, aliases);
  const href = `/run/${run.run_id}?evidence=/sample-pack-${run.run_id}.json`;
  const goToRun = () => navigate(href);
  return (
    <tr
      className="border-b border-border last:border-b-0 cursor-pointer hover:bg-bg/50 transition-colors"
      onClick={goToRun}
      role="button"
      tabIndex={0}
      onKeyDown={(e) => {
        if (e.key === "Enter" || e.key === " ") {
          e.preventDefault();
          goToRun();
        }
      }}
    >
      <td className="px-3 py-2.5 text-sm text-text" title={run.started_at}>
        {formatStartedAt(run.started_at)}
      </td>
      <td className="px-3 py-2.5 text-sm text-text">{run.agent_id}</td>
      <td className="px-3 py-2.5 text-sm text-text">
        {subject ? (
          <>
            {subject.primary}
            {subject.secondary && (
              <span className="text-muted text-xs ml-1">
                ({subject.secondary})
              </span>
            )}
          </>
        ) : (
          <span className="text-muted">—</span>
        )}
      </td>
      <td className={`px-3 py-2.5 text-sm uppercase ${decisionClasses(run.final_decision)}`}>
        {run.final_decision ?? "—"}
      </td>
      <td className="px-3 py-2.5 text-sm text-text">{run.event_count}</td>
      <td className="px-3 py-2.5 text-sm text-text">
        {formatDuration(run.duration_ms)}
      </td>
      <td className="px-3 py-2.5 text-sm">
        <a
          href={basescanTxUrl(run.anchor_tx)}
          target="_blank"
          rel="noreferrer"
          title={`${run.anchor_tx} (block ${run.anchor_block})`}
          className="text-ok no-underline hover:underline"
          onClick={(e) => e.stopPropagation()}
        >
          ✓
        </a>
      </td>
    </tr>
  );
}

function RunsTable({
  runs,
  aliases,
}: {
  runs: RunEntry[];
  aliases: SubjectAliases;
}) {
  return (
    <div className="bg-panel border border-border rounded-lg overflow-hidden">
      <table className="w-full">
        <thead>
          <tr className="text-xs uppercase tracking-wider text-muted text-left border-b border-border">
            <th className="px-3 py-2 font-medium">Time</th>
            <th className="px-3 py-2 font-medium">Agent</th>
            <th className="px-3 py-2 font-medium">Subject</th>
            <th className="px-3 py-2 font-medium">Decision</th>
            <th className="px-3 py-2 font-medium">Events</th>
            <th className="px-3 py-2 font-medium">Duration</th>
            <th className="px-3 py-2 font-medium">Anchored</th>
          </tr>
        </thead>
        <tbody>
          {runs.map((r) => (
            <RunsTableRow key={r.run_id} run={r} aliases={aliases} />
          ))}
        </tbody>
      </table>
    </div>
  );
}

// --- public component ------------------------------------------------------

export default function RunsListPage() {
  const navigate = useNavigate();

  // B6 self-contained HTML mode lands on / by default; if we detect an
  // embedded evidence pack, jump straight to its run page. Same redirect
  // LandingPage uses; without it, recipients of an evidence-bundle.html
  // would see the "No runs yet" empty state instead of the verifier UI.
  useEffect(() => {
    let pack;
    try {
      pack = loadFromEmbedded();
    } catch {
      return;
    }
    if (pack) {
      navigate(`/run/${pack.run_id}`, { replace: true });
    }
  }, [navigate]);

  const { state, aliases } = useRunsListData();

  const agentId = useMemo<string | null>(() => {
    if (state.kind !== "ok" || state.index.runs.length === 0) return null;
    return state.index.runs[0]!.agent_id;
  }, [state]);

  return (
    <div className="space-y-6">
      <PageHeader agentId={agentId} />

      {state.kind === "loading" && (
        <div className="text-muted text-sm">Loading runs…</div>
      )}
      {state.kind === "missing" && <EmptyState reason="missing" />}
      {state.kind === "empty" && <EmptyState reason="empty" />}
      {state.kind === "error" && <ErrorBanner message={state.message} />}
      {state.kind === "ok" && (
        <>
          <RunsTable runs={state.index.runs} aliases={aliases} />
          <div className="text-xs text-muted">
            {state.index.runs.length} run
            {state.index.runs.length === 1 ? "" : "s"} · index generated{" "}
            {state.index.generated_at}
          </div>
        </>
      )}
    </div>
  );
}
