"""CRUD for the run_summaries table — natural-language audit-trail summaries.

The summary itself is generated by an LLM (Phase C1, not this module) — this
file is pure storage. A summary describes what an agent did across a run in
3-5 sentences; storing it separately from receipts means the receipts stay
the law-grade evidence and the summary stays the convenience layer.

Per D2 in the v0.2 PLAN, summaries are NOT included in the Merkle tree by
default (`included_in_merkle=0`). Tier 3 customers can opt in per-run; when
they do, the summary's sha256 becomes a Merkle leaf alongside the receipts.

The schema lives in `chain.py::_SCHEMA` (one source of truth). Any operation
here briefly instantiates ReceiptChain to run that idempotent migration
before opening its own short-lived sqlite3 connection — so this module
works whether or not the caller has already touched the DB this session.
"""
from __future__ import annotations

import hashlib
import os
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .chain import ReceiptChain


def _default_db_path() -> Path:
    return Path(os.getenv("PROMPTSEAL_DB_PATH", "./promptseal.sqlite"))


def _now_iso() -> str:
    return (
        datetime.now(timezone.utc)
        .isoformat(timespec="milliseconds")
        .replace("+00:00", "Z")
    )


def _compute_summary_hash(text: str) -> str:
    """`sha256:` + lowercase hex digest of `text` encoded as UTF-8.

    Deterministic: the same text always produces the same hash. This is the
    value that becomes a Merkle leaf when `included_in_merkle=1`.
    """
    return "sha256:" + hashlib.sha256(text.encode("utf-8")).hexdigest()


def _open(db_path: Path | None) -> sqlite3.Connection:
    """Ensure the schema exists, then open a Row-mode connection with FKs on.

    We instantiate ReceiptChain once to run its idempotent migration (cheap;
    it's all `CREATE TABLE IF NOT EXISTS`), close that handle, then return a
    fresh connection. This keeps schema definition in chain.py only.
    """
    path = Path(db_path) if db_path is not None else _default_db_path()
    ReceiptChain(path).close()
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def _row_to_dict(row: sqlite3.Row) -> dict[str, Any]:
    """Translate a row into a JSON-serializable dict.

    `included_in_merkle` is exposed as a bool to callers (DB stores 0/1 per
    SQLite convention).
    """
    return {
        "run_id": row["run_id"],
        "summary_text": row["summary_text"],
        "summary_hash": row["summary_hash"],
        "generated_at": row["generated_at"],
        "llm_provider": row["llm_provider"],
        "llm_model": row["llm_model"],
        "included_in_merkle": bool(row["included_in_merkle"]),
    }


def insert_run_summary(
    run_id: str,
    summary_text: str,
    llm_provider: str,
    llm_model: str,
    included_in_merkle: bool = False,
    *,
    db_path: Path | None = None,
    generated_at: str | None = None,
) -> dict[str, Any]:
    """Store a summary for `run_id`. Returns the stored row as a dict.

    Raises sqlite3.IntegrityError if `run_id` does not exist in `runs`
    (FK constraint) or if a summary for `run_id` already exists (PRIMARY
    KEY constraint).
    """
    conn = _open(db_path)
    try:
        ts = generated_at or _now_iso()
        h = _compute_summary_hash(summary_text)
        conn.execute(
            """INSERT INTO run_summaries
               (run_id, summary_text, summary_hash, generated_at,
                llm_provider, llm_model, included_in_merkle)
               VALUES (?, ?, ?, ?, ?, ?, ?)""",
            (run_id, summary_text, h, ts, llm_provider, llm_model,
             1 if included_in_merkle else 0),
        )
        conn.commit()
        row = conn.execute(
            "SELECT * FROM run_summaries WHERE run_id = ?", (run_id,)
        ).fetchone()
        return _row_to_dict(row)
    finally:
        conn.close()


def load_run_summary(
    run_id: str, *, db_path: Path | None = None
) -> dict[str, Any] | None:
    """Return the summary for `run_id`, or None if none stored."""
    conn = _open(db_path)
    try:
        row = conn.execute(
            "SELECT * FROM run_summaries WHERE run_id = ?", (run_id,)
        ).fetchone()
        return _row_to_dict(row) if row else None
    finally:
        conn.close()


def list_run_summaries(*, db_path: Path | None = None) -> list[dict[str, Any]]:
    """All stored summaries, newest first (by generated_at)."""
    conn = _open(db_path)
    try:
        rows = conn.execute(
            "SELECT * FROM run_summaries ORDER BY generated_at DESC"
        ).fetchall()
        return [_row_to_dict(r) for r in rows]
    finally:
        conn.close()


def delete_run_summary(run_id: str, *, db_path: Path | None = None) -> bool:
    """Delete the summary for `run_id`. Returns True iff a row was removed."""
    conn = _open(db_path)
    try:
        cur = conn.execute(
            "DELETE FROM run_summaries WHERE run_id = ?", (run_id,)
        )
        conn.commit()
        return cur.rowcount > 0
    finally:
        conn.close()
